services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      # These use the values from .env file
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}    
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      # Runs schema.sql on startup
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

      # This keeps data alive even if the container restarts
      - mysql_data:/var/lib/mysql

   

  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      DB_HOST: db 
    
    volumes:
      #  Previous .env
      - ./.env:/app/.env 

      # Mounts persistent user uploads from the host disk.
      - ./apps/shared/public/media:/app/cdn/media
      - ./apps/shared/public/profile_images:/app/cdn/profile_images

volumes:
  mysql_data: