services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      # These use the values from .env file
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}    
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      # Runs schema.sql on startup
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

      # This keeps data alive even if the container restarts
      - mysql_data:/var/lib/mysql

   

  app:
    image: ghcr.io/ccloverdev/social-media-demo:latest
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    environment:
      DB_HOST: db 
    restart: unless-stopped
  
    volumes:
      #  .env
      - ./.env:/app/.env 

      # Mounts persistent user uploads from the host disk.
      - ./apps/media:/app/apps/shared/public/media
      - ./apps/profile_images:/app/apps/shared/public/profile_images

volumes:
  mysql_data: