name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/github_social_deploy
          chmod 600 ~/.ssh/github_social_deploy
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Sync files with rsync
        run: |
          rsync \
            -e "ssh -i ~/.ssh/github_social_deploy"
            -avzr --delete \
            --exclude='.git/' \
            --exclude='.github/' \
            --exclude='.env' \
            --exclude='node_modules/' \
            --exclude='cdn/media/*' \
            --exclude='cdn/profile_images/*' \
            ./ ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/webhost/servers/social_media_demo/

      - name: Restart Docker containers
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd /home/webhost/servers/social_media_demo/ && docker-compose up -d --build"